In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
import numpy

In [3]:
import numpy
arr=numpy.array([1,2,3,4,5,6])
print(arr)


[1 2 3 4 5 6]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [5]:
#checking numpy version
import numpy as np
print(np.__version__)

1.26.4


In [6]:
#0-D Array
import numpy as np
arr=np.array(45)
print(arr)


45


In [7]:
#1-D array
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
#2-D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
#check number of dimension
import numpy as np
a=np.array(45)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
#higher dimensional array
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimension :',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension : 5


In [19]:
#Access array element
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [20]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])

2


In [21]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1]+arr[2])

5


In [22]:
#access 2-D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [24]:
#Access 3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [25]:
#negative indexing
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim',arr[1,-1])

Last element from 2nd dim 10


In [26]:
#slicing array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [28]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [29]:
#Negative slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [30]:
#STEP
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [31]:
#Slicing 2-D array
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[::2])

[[1 2 3 4 5]]


In [33]:
#checking the data type of an array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.dtype)

int32


In [34]:
import numpy as np
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [36]:
#creating array with defined datatype
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [38]:
import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [39]:
#converting datatype on existing array
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [40]:
import numpy as np 
arr=np.array([1.1,2.1,3.1])
newarr-arr.astype('int')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [41]:
#COPY
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [42]:
#VIEW
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [44]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[1]=32
print(arr)
print(x)

[ 1 32  3  4  5]
[ 1 32  3  4  5]


In [45]:
#check if array own its data
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [46]:
#Get the shape of an array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [47]:
#Reshape from 1-D to 2-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
#check if return copy or view 
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [49]:
#Uknown dimension
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
#Flattening the array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [51]:
#Iterating array
import numpy as np
arr=np.array([1,2,3,4])
for x in arr:
    print(x)

1
2
3
4


In [52]:
#Iterating 2-D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [53]:
#Iterating 3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
#Iterator down to the sclaers
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9


In [55]:
#Iterating array using nditer()
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(arr):
    print(x)
    

1
2
3
4
5
6
7
8
9


In [57]:
#Iterating array using different datatype
import numpy as np
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [58]:
#Iterating with different size
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [60]:
#enumerated iteration using ndenumerate()
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [61]:
#Joining numpy array
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [62]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [63]:
#joining using stack function
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [64]:
#Stocking along rows
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [65]:
#Stacking along columns
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [66]:
#Stacking along height(depth)
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [67]:
#spliting numpy array
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [68]:
#split into array
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [69]:
#spliting into 2-D array
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [71]:
#Searching array
import numpy as np
arr=np.array([1,2,2,3,4,2,4,5])
newarr=np.where(arr==2)
print(newarr)

(array([1, 2, 5], dtype=int64),)


In [72]:
#find the index where value are even
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.where(arr%2==0)
print(newarr)

(array([1, 3, 5, 7], dtype=int64),)


In [73]:
#search sorted
import numpy as np
arr=np.array([2,3,5,7,8])
newarr=np.searchsorted(arr,7)
print(x)

3


In [74]:
import numpy as np
arr=np.array([6,7,8,9])
newarr=np.searchsorted(arr,7,side='right')
print(newarr)

2


In [75]:
#multiple value
import numpy as np
arr=np.array([1,3,5,7])
newarr=np.searchsorted(arr,[2,4,6])
print(newarr)

[1 2 3]


In [76]:
#sorting array
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [80]:
import numpy as np
arr=np.array(["banana","kiwi","cherry","apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'kiwi']


In [81]:
#Sorting 2-D array
import numpy as np
arr=np.array([[4,3,2],[8,1,3]])
print(np.sort(arr))

[[2 3 4]
 [1 3 8]]


In [82]:
#Filtering array
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,True]
newarr=arr[x]
print(newarr)

[41 43 44]


In [83]:
#creating a filter array
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [84]:
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True]
[42 44]


In [85]:
#creating filter from directing array
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [86]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False  True]
[2 4 6 8]
